<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

class NativeShieldSeeder extends Seeder
{
    /**
     * The exact permission names as generated by Filament Shield on the
     * production MySQL database. These must match 1-to-1 so that the
     * super_admin role works correctly on the NativePHP SQLite build.
     */
    protected array $permissions = [
        // --- Role management ---
        'view_role', 'view_any_role', 'create_role', 'update_role',
        'delete_role', 'delete_any_role',

        // --- Activity Log ---
        'view_activitylog', 'view_any_activitylog', 'create_activitylog',
        'update_activitylog', 'restore_activitylog', 'restore_any_activitylog',
        'replicate_activitylog', 'reorder_activitylog', 'delete_activitylog',
        'delete_any_activitylog', 'force_delete_activitylog', 'force_delete_any_activitylog',

        // --- Asset ---
        'view_asset', 'view_any_asset', 'create_asset', 'update_asset',
        'restore_asset', 'restore_any_asset', 'replicate_asset', 'reorder_asset',
        'delete_asset', 'delete_any_asset', 'force_delete_asset', 'force_delete_any_asset',

        // --- Asset Category ---
        'view_asset::category', 'view_any_asset::category', 'create_asset::category',
        'update_asset::category', 'restore_asset::category', 'restore_any_asset::category',
        'replicate_asset::category', 'reorder_asset::category', 'delete_asset::category',
        'delete_any_asset::category', 'force_delete_asset::category', 'force_delete_any_asset::category',

        // --- Borrower ---
        'view_borrower', 'view_any_borrower', 'create_borrower', 'update_borrower',
        'restore_borrower', 'restore_any_borrower', 'replicate_borrower', 'reorder_borrower',
        'delete_borrower', 'delete_any_borrower', 'force_delete_borrower', 'force_delete_any_borrower',

        // --- Branches ---
        'view_branches', 'view_any_branches', 'create_branches', 'update_branches',
        'restore_branches', 'restore_any_branches', 'replicate_branches', 'reorder_branches',
        'delete_branches', 'delete_any_branches', 'force_delete_branches', 'force_delete_any_branches',

        // --- Bulk Repayments ---
        'view_bulk::repayments', 'view_any_bulk::repayments', 'create_bulk::repayments',
        'update_bulk::repayments', 'restore_bulk::repayments', 'restore_any_bulk::repayments',
        'replicate_bulk::repayments', 'reorder_bulk::repayments', 'delete_bulk::repayments',
        'delete_any_bulk::repayments', 'force_delete_bulk::repayments', 'force_delete_any_bulk::repayments',

        // --- Contact Messages ---
        'view_contact::messages', 'view_any_contact::messages', 'create_contact::messages',
        'update_contact::messages', 'restore_contact::messages', 'restore_any_contact::messages',
        'replicate_contact::messages', 'reorder_contact::messages', 'delete_contact::messages',
        'delete_any_contact::messages', 'force_delete_contact::messages', 'force_delete_any_contact::messages',

        // --- Direct Debit Mandate Settings ---
        'view_direct::debit::mandate::settings', 'view_any_direct::debit::mandate::settings',
        'create_direct::debit::mandate::settings', 'update_direct::debit::mandate::settings',
        'restore_direct::debit::mandate::settings', 'restore_any_direct::debit::mandate::settings',
        'replicate_direct::debit::mandate::settings', 'reorder_direct::debit::mandate::settings',
        'delete_direct::debit::mandate::settings', 'delete_any_direct::debit::mandate::settings',
        'force_delete_direct::debit::mandate::settings', 'force_delete_any_direct::debit::mandate::settings',

        // --- Employee ---
        'view_employee', 'view_any_employee', 'create_employee', 'update_employee',
        'restore_employee', 'restore_any_employee', 'replicate_employee', 'reorder_employee',
        'delete_employee', 'delete_any_employee', 'force_delete_employee', 'force_delete_any_employee',

        // --- Expense ---
        'view_expense', 'view_any_expense', 'create_expense', 'update_expense',
        'restore_expense', 'restore_any_expense', 'replicate_expense', 'reorder_expense',
        'delete_expense', 'delete_any_expense', 'force_delete_expense', 'force_delete_any_expense',

        // --- Expense Category ---
        'view_expense::category', 'view_any_expense::category', 'create_expense::category',
        'update_expense::category', 'restore_expense::category', 'restore_any_expense::category',
        'replicate_expense::category', 'reorder_expense::category', 'delete_expense::category',
        'delete_any_expense::category', 'force_delete_expense::category', 'force_delete_any_expense::category',

        // --- Loan ---
        'view_loan', 'view_any_loan', 'create_loan', 'update_loan',
        'restore_loan', 'restore_any_loan', 'replicate_loan', 'reorder_loan',
        'delete_loan', 'delete_any_loan', 'force_delete_loan', 'force_delete_any_loan',

        // --- Loan Agreement Forms ---
        'view_loan::agreement::forms', 'view_any_loan::agreement::forms',
        'create_loan::agreement::forms', 'update_loan::agreement::forms',
        'restore_loan::agreement::forms', 'restore_any_loan::agreement::forms',
        'replicate_loan::agreement::forms', 'reorder_loan::agreement::forms',
        'delete_loan::agreement::forms', 'delete_any_loan::agreement::forms',
        'force_delete_loan::agreement::forms', 'force_delete_any_loan::agreement::forms',

        // --- Loan Restructure ---
        'view_loan::restructure', 'view_any_loan::restructure', 'create_loan::restructure',
        'update_loan::restructure', 'restore_loan::restructure', 'restore_any_loan::restructure',
        'replicate_loan::restructure', 'reorder_loan::restructure', 'delete_loan::restructure',
        'delete_any_loan::restructure', 'force_delete_loan::restructure', 'force_delete_any_loan::restructure',

        // --- Loan Roll Over ---
        'view_loan::roll::over', 'view_any_loan::roll::over', 'create_loan::roll::over',
        'update_loan::roll::over', 'restore_loan::roll::over', 'restore_any_loan::roll::over',
        'replicate_loan::roll::over', 'reorder_loan::roll::over', 'delete_loan::roll::over',
        'delete_any_loan::roll::over', 'force_delete_loan::roll::over', 'force_delete_any_loan::roll::over',

        // --- Loan Settlement Forms ---
        'view_loan::settlement::forms', 'view_any_loan::settlement::forms',
        'create_loan::settlement::forms', 'update_loan::settlement::forms',
        'restore_loan::settlement::forms', 'restore_any_loan::settlement::forms',
        'replicate_loan::settlement::forms', 'reorder_loan::settlement::forms',
        'delete_loan::settlement::forms', 'delete_any_loan::settlement::forms',
        'force_delete_loan::settlement::forms', 'force_delete_any_loan::settlement::forms',

        // --- Loan Type ---
        'view_loan::type', 'view_any_loan::type', 'create_loan::type', 'update_loan::type',
        'restore_loan::type', 'restore_any_loan::type', 'replicate_loan::type', 'reorder_loan::type',
        'delete_loan::type', 'delete_any_loan::type', 'force_delete_loan::type', 'force_delete_any_loan::type',

        // --- Messages ---
        'view_messages', 'view_any_messages', 'create_messages', 'update_messages',
        'restore_messages', 'restore_any_messages', 'replicate_messages', 'reorder_messages',
        'delete_messages', 'delete_any_messages', 'force_delete_messages', 'force_delete_any_messages',

        // --- Payroll Run ---
        'view_payroll::run', 'view_any_payroll::run', 'create_payroll::run', 'update_payroll::run',
        'restore_payroll::run', 'restore_any_payroll::run', 'replicate_payroll::run', 'reorder_payroll::run',
        'delete_payroll::run', 'delete_any_payroll::run', 'force_delete_payroll::run', 'force_delete_any_payroll::run',

        // --- Payslip ---
        'view_payslip', 'view_any_payslip', 'create_payslip', 'update_payslip',
        'restore_payslip', 'restore_any_payslip', 'replicate_payslip', 'reorder_payslip',
        'delete_payslip', 'delete_any_payslip', 'force_delete_payslip', 'force_delete_any_payslip',

        // --- Repayments ---
        'view_repayments', 'view_any_repayments', 'create_repayments', 'update_repayments',
        'restore_repayments', 'restore_any_repayments', 'replicate_repayments', 'reorder_repayments',
        'delete_repayments', 'delete_any_repayments', 'force_delete_repayments', 'force_delete_any_repayments',

        // --- Salary Scale ---
        'view_salary::scale', 'view_any_salary::scale', 'create_salary::scale', 'update_salary::scale',
        'restore_salary::scale', 'restore_any_salary::scale', 'replicate_salary::scale', 'reorder_salary::scale',
        'delete_salary::scale', 'delete_any_salary::scale', 'force_delete_salary::scale', 'force_delete_any_salary::scale',

        // --- Subscriptions ---
        'view_subscriptions', 'view_any_subscriptions', 'create_subscriptions', 'update_subscriptions',
        'restore_subscriptions', 'restore_any_subscriptions', 'replicate_subscriptions', 'reorder_subscriptions',
        'delete_subscriptions', 'delete_any_subscriptions', 'force_delete_subscriptions', 'force_delete_any_subscriptions',

        // --- Switch Branch ---
        'view_switch::branch', 'view_any_switch::branch', 'create_switch::branch', 'update_switch::branch',
        'restore_switch::branch', 'restore_any_switch::branch', 'replicate_switch::branch', 'reorder_switch::branch',
        'delete_switch::branch', 'delete_any_switch::branch', 'force_delete_switch::branch', 'force_delete_any_switch::branch',

        // --- Tax Band ---
        'view_tax::band', 'view_any_tax::band', 'create_tax::band', 'update_tax::band',
        'restore_tax::band', 'restore_any_tax::band', 'replicate_tax::band', 'reorder_tax::band',
        'delete_tax::band', 'delete_any_tax::band', 'force_delete_tax::band', 'force_delete_any_tax::band',

        // --- Third Party ---
        'view_third::party', 'view_any_third::party', 'create_third::party', 'update_third::party',
        'restore_third::party', 'restore_any_third::party', 'replicate_third::party', 'reorder_third::party',
        'delete_third::party', 'delete_any_third::party', 'force_delete_third::party', 'force_delete_any_third::party',

        // --- Transactions ---
        'view_transactions', 'view_any_transactions', 'create_transactions', 'update_transactions',
        'restore_transactions', 'restore_any_transactions', 'replicate_transactions', 'reorder_transactions',
        'delete_transactions', 'delete_any_transactions', 'force_delete_transactions', 'force_delete_any_transactions',

        // --- Transfers ---
        'view_transfers', 'view_any_transfers', 'create_transfers', 'update_transfers',
        'restore_transfers', 'restore_any_transfers', 'replicate_transfers', 'reorder_transfers',
        'delete_transfers', 'delete_any_transfers', 'force_delete_transfers', 'force_delete_any_transfers',

        // --- User ---
        'view_user', 'view_any_user', 'create_user', 'update_user',
        'restore_user', 'restore_any_user', 'replicate_user', 'reorder_user',
        'delete_user', 'delete_any_user', 'force_delete_user', 'force_delete_any_user',

        // --- Wallet ---
        'view_wallet', 'view_any_wallet', 'create_wallet', 'update_wallet',
        'restore_wallet', 'restore_any_wallet', 'replicate_wallet', 'reorder_wallet',
        'delete_wallet', 'delete_any_wallet', 'force_delete_wallet', 'force_delete_any_wallet',

        // --- Account ---
        'view_account', 'view_any_account', 'create_account', 'update_account',
        'restore_account', 'restore_any_account', 'replicate_account', 'reorder_account',
        'delete_account', 'delete_any_account', 'force_delete_account', 'force_delete_any_account',

        // --- Journal Entry ---
        'view_journal::entry', 'view_any_journal::entry', 'create_journal::entry',
        'update_journal::entry', 'restore_journal::entry', 'restore_any_journal::entry',
        'replicate_journal::entry', 'reorder_journal::entry', 'delete_journal::entry',
        'delete_any_journal::entry', 'force_delete_journal::entry', 'force_delete_any_journal::entry',

        // --- Pages ---
        'page_ProfileCompletion',
        'page_StatementOfFinancialPosition',
        'page_StatementOfComprehensiveIncome',
        'page_CashFlowStatement',
        'page_GeneralLedger',
        'page_TrialBalance',

        // --- Widgets ---
        'widget_StatsOverview',
        'widget_PrincipleReleased',
        'widget_TotalCollected',
        'widget_Expenses',
        'widget_OutstandingBalance',
    ];

    public function run(): void
    {
        // Reset cached roles and permissions
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $guardName = 'web';

        // --- Create all permissions (upsert so re-running is safe) ---
        foreach ($this->permissions as $permissionName) {
            Permission::firstOrCreate([
                'name'       => $permissionName,
                'guard_name' => $guardName,
            ]);
        }

        // --- Create super_admin role and assign ALL permissions ---
        $superAdminRole = Role::firstOrCreate([
            'name'       => 'super_admin',
            'guard_name' => $guardName,
        ]);

        $superAdminRole->syncPermissions(
            Permission::where('guard_name', $guardName)->get()
        );

        // --- Assign super_admin to the first user if they don't already have it ---
        $firstUser = \App\Models\User::first();
        if ($firstUser && !$firstUser->hasRole('super_admin')) {
            $firstUser->assignRole($superAdminRole);
        }

        $this->command?->info('✅ Shield permissions and roles seeded successfully for NativePHP.');
    }
}
